name: JSDox

on:
	workflow_dispatch:
	branches: [ master ]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Generate JSDoc documentation
			uses: brunokrauss/jsdoc-action@3
			with:
				jsdoc-path: 'src'
